* Remove unused include * Fix error build with  ZENLIB_DEBUG
git clone https://github.com/MediaArea/ZenLib.git
cd ZenLib\Project\MSVC2015
call "%VS140COMNTOOLS%\..\..\VC\bin\vcvars32.bat"
SET CL=/DZENLIB_DEBUG
"%VS140COMNTOOLS%..\ide\devenv" ZenLib_MSVC.sln /Rebuild "Debug|Win32"

D:\git-test>cd ZenLib\Project\MSVC2015

D:\git-test\ZenLib\Project\MSVC2015>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\bin\vcvars32.bat"

D:\git-test\ZenLib\Project\MSVC2015>SET CL=/DZENLIB_DEBUG

D:\git-test\ZenLib\Project\MSVC2015>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\ide\devenv" ZenLib_MSVC.sln /Rebuild "Debug|Win32"

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.
1>------ Rebuild All started: Project: ZenLib, Configuration: Debug Win32 ------
1>  PreComp.cpp
1>  Conf.cpp
1>  CriticalSection.cpp
1>  Dir.cpp
1>  File.cpp
1>  FileName.cpp
1>  HTTP_Client.cpp
1>  InfoMap.cpp
1>  int128s.cpp
1>  int128u.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1435): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1437): note: see reference to class template instantiation 'std::unique_ptr<_Ty,_Dx>' being compiled (compiling source file ..\..\..\Source\ZenLib\int128s
.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1435): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1437): note: see reference to class template instantiation 'std::unique_ptr<_Ty,_Dx>' being compiled (compiling source file ..\..\..\Source\ZenLib\int128u
.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1435): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1435): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1436): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1436): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1436): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1436): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1611): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1621): note: see reference to class template instantiation 'std::unique_ptr<_Ty[],_Dx>' being compiled (compiling source file ..\..\..\Source\ZenLib\int12
8s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1611): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1613): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1613): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128s.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1611): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1621): note: see reference to class template instantiation 'std::unique_ptr<_Ty[],_Dx>' being compiled (compiling source file ..\..\..\Source\ZenLib\int12
8u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1611): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1613): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1613): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\int128u.cpp)
1>  MemoryDebug.cpp
1>  OS_Utils.cpp
1>  Thread.cpp
1>  Translation.cpp
1>  Utils.cpp
1>  Ztring.cpp
1>  ZtringList.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(116): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\ZtringList.cpp)
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(127): note: see reference to class template instantiation 'std::_Func_base<_Rx,_Types...>' being compiled (compiling source file ..\..\..\Source\ZenLi
b\ZtringList.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(116): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\ZtringList.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(117): error C2061: syntax error: identifier 'Instance' (compiling source file ..\..\..\Source\ZenLib\ZtringList.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(117): error C2238: unexpected token(s) preceding ';' (compiling source file ..\..\..\Source\ZenLib\ZtringList.cpp)
1>  ZtringListList.cpp
1>  ZtringListListF.cpp
1>  Http_Cookies.cpp
1>  Http_Handler.cpp
1>  Http_Request.cpp
1>  Http_Utils.cpp
1>  Html_Handler.cpp
1>  Html_Request.cpp
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========